baseurl = "https://hernandezluis.com/resume"
title = "Winning"
theme = "winning"
#themesdir = "../.."

disableKinds = ["RSS"]
defaultContentLanguage = "en"
enableRobotsTXT = true
languageCode = "en-us"
[taxonomies]

[params]
header_background = "img/caltech.png"

[author]
    name = "your-name"
    email = "your-email"
