baseurl = "https://hernandezluis.com"
title = "Luis Hernandez"
theme = "winning"
#themesdir = "../.."

disableKinds = ["RSS"]
defaultContentLanguage = "en"
enableRobotsTXT = true
languageCode = "en-us"
[taxonomies]

[params]
header_background = "img/caltech.png"

[author]
    name = "your-name"
    email = "your-email"
