baseurl = "https://example.com"
title = "Winning"
theme = "winning"
#themesdir = "../.."

disableKinds = ["RSS"]
defaultContentLanguage = "en"
#enableRobotsTXT = true
languageCode = "en-us"
[taxonomies]

[author]
    name = "your-name"
    email = "your-email"
